apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-realtime
  name: {{ .Release.Name }}-realtime
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
  selector:
    io.kompose.service: {{ .Release.Name }}-realtime
status:
  loadBalancer: {}
