apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-realtime
  name: {{ .Release.Name }}-realtime
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Release.Name }}-realtime
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Release.Name }}-realtime
    spec:
      containers:
        - args:
            - bash
            - -c
            - ./prod/rel/realtime/bin/realtime eval Realtime.Release.migrate && ./prod/rel/realtime/bin/realtime start
          env:
            - name: DB_HOST
              value: my-supabase-db # TODO: fix
            - name: DB_NAME
              value: postgres
            - name: DB_PASSWORD
              value: test # TODO: fix
            - name: DB_PORT
              value: "5432"
            - name: DB_SSL
              value: "false"
            - name: DB_USER
              value: postgres
            - name: JWT_SECRET
              value: todo # TODO: fix
            - name: PORT
              value: "4000"
            - name: REPLICATION_MODE
              value: RLS
            - name: REPLICATION_POLL_INTERVAL
              value: "100"
            - name: SECURE_CHANNELS
              value: "true"
            - name: SLOT_NAME
              value: supabase_realtime_rls
            - name: TEMPORARY_SLOT
              value: "true"
          image: supabase/realtime:v0.19.3
          name: supabase-realtime
          resources: {}
      initContainers:
        - name: check-db-ready
          image: postgres:9.6.5
          command: ['sh', '-c', 
            'until pg_isready -h my-supabase-db -p 5432; 
            do echo waiting for database; sleep 2; done;']
      restartPolicy: Always
status: {}
