apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-storage
  name: {{ .Release.Name }}-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Release.Name }}-storage
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Release.Name }}-storage
    spec:
      containers:
        - env:
            - name: ANON_KEY
            - name: DATABASE_URL
              value: postgres://postgres:@db:5432/postgres
            - name: FILE_SIZE_LIMIT
              value: "52428800"
            - name: FILE_STORAGE_BACKEND_PATH
              value: /var/lib/storage
            - name: GLOBAL_S3_BUCKET
              value: stub
            - name: PGOPTIONS
              value: -c search_path=storage,public
            - name: PGRST_JWT_SECRET
            - name: POSTGREST_URL
              value: http://rest:3000
            - name: REGION
              value: stub
            - name: SERVICE_KEY
            - name: STORAGE_BACKEND
              value: file
            - name: TENANT_ID
              value: stub
          image: supabase/storage-api:v0.10.0
          name: supabase-storage
          resources: {}
      restartPolicy: Always
status: {}
